### ISSUE TITLE
Unmanaged error when forgetting to choose an output file

### ISSUE THREAD

**Issue by pcav** [dtutic/CartoLineGen#3]
AttributeError: 'NoneType' object has no attribute 'CreateLayer' 
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/CartoLineGen-master/cartolinegen.py", line 248, in generalize
    generalize.Generalize(scale,area,inFile,outFile)
  File "/home/paolo/.qgis2/python/plugins/CartoLineGen-master/generalize.py", line 429, in Generalize
    outLayer = outDataSet.CreateLayer(inLayer.GetName(), geom_type=inLayer.GetGeomType())
AttributeError: 'NoneType' object has no attribute 'CreateLayer'

**Comment by dtutic** [comment]
Yes I saw it. Thanks. I will fix it today.

**Comment by pcav** [comment]
I have flagged it as experimental, because of these issues.

**Comment by dtutic** [comment]
Thanks.

**Comment by dtutic** [comment]
Fixed. Error is now reported.
